<script setup lang="ts">
import { ref } from 'vue'

type DbItem = {
  name: string
  expanded: boolean
  tables: string[]
}

type ChatItem = {
  id: string
  user: string
  ai: string
  queryLink?: string
}

type QueryItem = {
  id: string
  text: string
  byAI: boolean
}

const activeTab = ref<'data' | 'chats' | 'queries'>('data')

/* Database Tree */
const databases = ref<DbItem[]>([
  { name: 'Pegasus_Main', expanded: true, tables: ['Users', 'Logs', 'Metrics'] },
  { name: 'Analytics', expanded: false, tables: ['Sessions', 'Events'] },
  { name: 'Archive', expanded: false, tables: ['Old_Users', 'Logs_2023'] }
])

/* Mock Data */
const chats = ref<ChatItem[]>([
  {
    id: '1',
    user: 'Show me logs from today',
    ai: 'Fetching today’s logs from Pegasus_Main.Logs...',
    queryLink: '/dashboard/logs'
  },
  {
    id: '2',
    user: 'Generate analytics summary',
    ai: 'Creating real-time dashboard from Analytics.Sessions'
  }
])

const queries = ref<QueryItem[]>([
  { id: 'q1', text: 'SELECT * FROM Logs WHERE date = TODAY', byAI: true },
  { id: 'q2', text: 'UPDATE Users SET Active = 0 WHERE LastLogin < 2022', byAI: false },
  { id: 'q3', text: 'SELECT COUNT(*) FROM Metrics', byAI: true }
])

const toggle = (db: DbItem) => (db.expanded = !db.expanded)
</script>

<template>
  <div class="flex flex-col h-full text-sm select-none">
    <!-- Tabs -->
    <div class="flex border-b border-stone-800">
      <button
        v-for="tab in ['data', 'chats', 'queries']"
        :key="tab"
        @click="activeTab = tab"
        class="flex-1 py-2 text-center capitalize transition-colors"
        :class="[
          activeTab === tab
            ? 'bg-stone-900 text-violet-400 font-semibold border-b-2 border-violet-500'
            : 'text-stone-400 hover:text-violet-300'
        ]"
      >
        {{ tab }}
      </button>
    </div>

    <!-- Scrollable area -->
    <div class="flex-1 overflow-y-auto p-2">
      <!-- Data Tab -->
      <template v-if="activeTab === 'data'">
        <h2 class="px-2 py-1 font-semibold text-violet-500">Databases</h2>
        <ul>
          <li
            v-for="db in databases"
            :key="db.name"
            class="mb-1 rounded hover:bg-stone-800/80 transition-colors"
          >
            <button
              class="flex w-full items-center justify-between px-3 py-1 text-left"
              @click="toggle(db)"
            >
              <span class="font-medium">{{ db.name }}</span>
              <span class="text-xs text-stone-400">{{ db.expanded ? '−' : '+' }}</span>
            </button>

            <ul
              v-show="db.expanded"
              class="pl-5 border-l border-stone-700/50 space-y-0.5 py-1"
            >
              <li
                v-for="table in db.tables"
                :key="table"
                class="flex items-center justify-between px-2 py-1 rounded hover:bg-violet-500/10 cursor-pointer"
              >
                <span class="truncate">{{ table }}</span>
                <span class="text-xs text-violet-500 opacity-75">tbl</span>
              </li>
            </ul>
          </li>
        </ul>
      </template>

      <!-- Chats Tab -->
      <template v-else-if="activeTab === 'chats'">
        <h2 class="px-2 py-1 font-semibold text-violet-500">Recent Chats</h2>
        <ul class="space-y-2 mt-1">
          <li
            v-for="chat in chats"
            :key="chat.id"
            class="p-2 rounded-lg bg-stone-900 hover:bg-stone-800/70 transition"
          >
            <p class="text-stone-200 text-sm font-medium">🧑 {{ chat.user }}</p>
            <p class="text-stone-400 text-xs mt-1">🤖 {{ chat.ai }}</p>
            <a
              v-if="chat.queryLink"
              :href="chat.queryLink"
              class="text-violet-400 text-xs underline mt-1 inline-block hover:text-violet-300"
            >
              View linked query
            </a>
          </li>
        </ul>
      </template>

      <!-- Past Queries Tab -->
      <template v-else>
        <h2 class="px-2 py-1 font-semibold text-violet-500">Past Queries</h2>
        <ul class="space-y-1 mt-1">
          <li
            v-for="q in queries"
            :key="q.id"
            class="flex items-center justify-between p-2 rounded-md hover:bg-stone-800/70 cursor-pointer transition"
          >
            <div class="flex items-center gap-2 truncate">
              <span
                v-if="q.byAI"
                class="inline-block w-4 h-4 bg-violet-600 rounded-sm"
                title="Generated by Pegasus AI"
              ></span>
              <span class="truncate text-stone-200 text-xs font-mono">
                {{ q.text }}
              </span>
            </div>
          </li>
        </ul>
      </template>
    </div>
  </div>
</template>
