import { defineStore } from 'pinia'
import { ref, computed, unref } from 'vue'
import { api } from '@/lib/apiClient'
import { useSpaceStore } from './space'

export interface ChatMessage {
    role: 'user' | 'assistant' | 'ai'
    content: string
    timestamp: number
    meta?: any
}

export interface Chat {
    id: string
    title: string
    messages: ChatMessage[]
    createdAt: number
    updatedAt: number
}

export const useChatStore = defineStore('chat', () => {
    // State
    const chats = ref<Chat[]>([])
    const selectedChatId = ref<string | null>(null)
    const isLoading = ref(false)
    const spaceStore = useSpaceStore()

    // Computed
    const selectedChat = computed(() =>
        chats.value.find(c => c.id === selectedChatId.value) || null
    )

    const selectedChatMessages = computed(() =>
        selectedChat.value?.messages || []
    )

    // Actions
    async function loadChats() {
        isLoading.value = true
        try {
            const currentSpaceId = unref(spaceStore.currentSpaceId)
            const spaceId = currentSpaceId?.split(':').pop()

            if (!spaceId) {
                chats.value = []
                isLoading.value = false
                return
            }

            const url = `/chats?space_id=${spaceId}`
            const response = await api.get<{ chats: Chat[] }>(url)
            chats.value = response.chats || []
            console.log('[ChatStore] Loaded chats:', chats.value.length)
        } catch (e) {
            console.error('[ChatStore] Failed to load chats:', e)
            chats.value = []
        } finally {
            isLoading.value = false
        }
    }

    async function createChat(title: string = 'New Chat') {
        try {
            const currentSpaceId = unref(spaceStore.currentSpaceId)
            const spaceId = currentSpaceId?.split(':').pop()
            const newChat = await api.post<Chat>('/chats', { title, space_id: spaceId })
            chats.value.unshift(newChat)
            selectedChatId.value = newChat.id
            console.log('[ChatStore] Created chat:', newChat.id)
            return newChat
        } catch (e) {
            console.error('[ChatStore] Failed to create chat:', e)
            throw e
        }
    }

    async function loadChatHistory(chatId: string) {
        isLoading.value = true
        try {
            const data = await api.get<{ messages: any[] }>(`/chats/${chatId}`)

            const messages: ChatMessage[] = data.messages.map((m: any) => ({
                role: m.role === 'ai' ? 'assistant' : m.role,
                content: m.content,
                timestamp: m.created_at * 1000,
                meta: m.meta
            }))

            // Update chat in store
            const chat = chats.value.find(c => c.id === chatId)
            if (chat) {
                chat.messages = messages
                chat.updatedAt = Date.now()
            }

            console.log('[ChatStore] Loaded chat history:', { chatId, messagesCount: messages.length })
            return messages
        } catch (e) {
            console.error('[ChatStore] Failed to load chat history:', e)
            throw e
        } finally {
            isLoading.value = false
        }
    }

    async function saveMessage(chatId: string, role: 'user' | 'ai', content: string, meta?: any, modelId?: string) {
        try {
            const response = await api.post<{ id: string; title?: string }>(`/chats/${chatId}/messages`, {
                role,
                content,
                meta,
                modelId
            })

            // Update local state
            const chat = chats.value.find(c => c.id === chatId)
            if (chat) {
                chat.messages.push({
                    role: role === 'ai' ? 'assistant' : role,
                    content,
                    timestamp: Date.now(),
                    meta
                })
                chat.updatedAt = Date.now()

                // Update title if returned (auto-generated by AI)
                if (response.title) {
                    chat.title = response.title
                    console.log('[ChatStore] Updated chat title:', response.title)

                    // Sync with Workspace Tabs
                    // We import here to avoid circular dependency issues if any, 
                    // though workspace doesn't depend on chat currently.
                    const { useWorkspaceStore } = await import('./workspace')
                    const workspaceStore = useWorkspaceStore()

                    // Find any tab displaying this chat
                    const tab = (workspaceStore.tabs as any).find((t: any) => t.data?.chatId === chatId)
                    if (tab) {
                        workspaceStore.updateTabData(tab.id, { label: response.title })
                        // Also update top-level label for immediate reactivity
                        tab.label = response.title
                    }
                }
            }

            console.log('[ChatStore] Saved message:', { chatId, role })
            return response
        } catch (e) {
            console.error('[ChatStore] Failed to save message:', e)
            throw e
        }
    }

    async function deleteChat(chatId: string) {
        try {
            await api.delete(`/chats/${chatId}`)

            const index = chats.value.findIndex(c => c.id === chatId)
            if (index !== -1) {
                chats.value.splice(index, 1)
            }

            if (selectedChatId.value === chatId) {
                selectedChatId.value = null
            }

            console.log('[ChatStore] Deleted chat:', chatId)
        } catch (e) {
            console.error('[ChatStore] Failed to delete chat:', e)
            throw e
        }
    }

    function selectChat(chatId: string | null) {
        selectedChatId.value = chatId
        console.log('[ChatStore] Selected chat:', chatId)
    }

    return {
        // State
        chats,
        selectedChatId,
        isLoading,

        // Computed
        selectedChat,
        selectedChatMessages,

        // Actions
        loadChats,
        createChat,
        loadChatHistory,
        saveMessage,
        deleteChat,
        selectChat
    }
})
